spring:
  h2.console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/webappdb
    username: sa
    password: sa

graphql:
  servlet:
    enabled: true
    exception-handlers-enabled: true
    mapping: /graphql

graphiql:
  enabled: true
  mapping: /graphiql
  endpoint:
    graphql: /graphql
logging:
  level:
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
